-- ========================================
-- AutoPulse Database Schema & Seed Data
-- ========================================

-- ========================================
-- 1. Создание таблиц
-- ========================================

-- Markets (Рынки)
CREATE TABLE IF NOT EXISTS "Markets" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Region" TEXT NOT NULL,
    "Currency" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Brands (Бренды)
CREATE TABLE IF NOT EXISTS "Brands" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Country" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Models (Модели)
CREATE TABLE IF NOT EXISTS "Models" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BrandId" INTEGER NOT NULL REFERENCES "Brands"("Id"),
    "Name" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Dealers (Дилеры)
CREATE TABLE IF NOT EXISTS "Dealers" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Rating" DECIMAL(2,1) NOT NULL,
    "ContactInfo" TEXT,
    "Address" TEXT,
    "MarketId" INTEGER NOT NULL REFERENCES "Markets"("Id"),
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE
);

-- Cars (Автомобили)
CREATE TABLE IF NOT EXISTS "Cars" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DealerId" INTEGER NOT NULL REFERENCES "Dealers"("Id"),
    "MarketId" INTEGER NOT NULL REFERENCES "Markets"("Id"),
    "BrandId" INTEGER NOT NULL REFERENCES "Brands"("Id"),
    "ModelId" INTEGER NOT NULL REFERENCES "Models"("Id"),
    "Year" INTEGER NOT NULL,
    "Price" DECIMAL(18,2) NOT NULL,
    "Currency" TEXT NOT NULL,
    "Mileage" INTEGER NOT NULL,
    "IsAvailable" BOOLEAN NOT NULL DEFAULT TRUE,
    "Description" TEXT,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE
);

-- DataSources (Источники данных)
CREATE TABLE IF NOT EXISTS "DataSources" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Country" TEXT NOT NULL,
    "BaseUrl" TEXT,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 2. Seed Data
-- ========================================

-- Markets
INSERT INTO "Markets" ("Name", "Region", "Currency")
VALUES 
('China', 'Asia', 'CNY'),
('USA', 'North America', 'USD'),
('Europe', 'Europe', 'EUR');

-- Brands
INSERT INTO "Brands" ("Name", "Country")
VALUES 
('Audi', 'Germany'),
('BMW', 'Germany'),
('Mercedes-Benz', 'Germany'),
('Toyota', 'Japan'),
('Honda', 'Japan'),
('Volkswagen', 'Germany'),
('BYD', 'China'),
('Geely', 'China');

-- Models
INSERT INTO "Models" ("BrandId", "Name")
VALUES 
(1, 'A8'),      -- Audi A8
(1, 'A6'),      -- Audi A6
(1, 'Q7'),      -- Audi Q7
(1, 'A4'),      -- Audi A4
(2, 'X5'),      -- BMW X5
(2, '3 Series'),-- BMW 3 Series
(3, 'S-Class'), -- Mercedes S-Class
(3, 'E-Class'), -- Mercedes E-Class
(4, 'Camry'),   -- Toyota Camry
(5, 'Civic');   -- Honda Civic

-- Dealers
INSERT INTO "Dealers" ("Name", "Rating", "ContactInfo", "Address", "MarketId")
VALUES 
('北京世纪双合旧机动车经纪有限公司', 4.8, '电话：+86-10-12345678', '北京丰台区南四环西路 123 号西厅 D 道', 1),
('北京奥迪官方经销商', 4.9, '电话：+86-10-87654321', '北京市朝阳区建国路 88 号', 1),
('上海二手车交易中心', 4.5, '电话：+86-21-11223344', '上海市浦东新区沪南路 500 号', 1),
('广州宝马授权经销商', 4.7, '电话：+86-20-99887766', '广州市天河区天河路 200 号', 1),
('深圳奔驰体验中心', 4.6, '电话：+86-755-66778899', '深圳市福田区深南大道 1000 号', 1);

-- Cars
INSERT INTO "Cars" ("DealerId", "MarketId", "BrandId", "ModelId", "Year", "Price", "Currency", "Mileage", "IsAvailable", "Description")
VALUES 
-- Audi A8 из HTML
(1, 1, 1, 1, 2023, 668000, 'CNY', 18000, TRUE, 
 'Audi A8L 55 TFSI quattro Flagship. Белый цвет, 3.0L V6, автоматическая коробка передач.'),

-- Дополнительные Audi
(2, 1, 1, 1, 2024, 720000, 'CNY', 5000, TRUE, 'Audi A8L 60 TFSI e quattro. Гибрид.'),
(1, 1, 1, 1, 2022, 580000, 'CNY', 35000, TRUE, 'Audi A8L 50 TDI quattro. Дизель.'),
(2, 1, 1, 2, 2023, 420000, 'CNY', 12000, TRUE, 'Audi A6L 45 TFSI quattro.'),
(3, 1, 1, 2, 2022, 380000, 'CNY', 28000, FALSE, 'Audi A6L 40 TFSI. Продан.'),
(1, 1, 1, 3, 2023, 680000, 'CNY', 15000, TRUE, 'Audi Q7 55 TFSI quattro. Внедорожник, 7 мест.'),

-- BMW
(4, 1, 2, 5, 2023, 750000, 'CNY', 10000, TRUE, 'BMW X5 xDrive40i. M-пакет.'),
(2, 1, 2, 5, 2022, 680000, 'CNY', 22000, TRUE, 'BMW X5 xDrive30d. Дизель.'),
(4, 1, 2, 6, 2023, 350000, 'CNY', 8000, TRUE, 'BMW 330i M Sport.'),

-- Mercedes-Benz
(5, 1, 3, 7, 2023, 980000, 'CNY', 6000, TRUE, 'Mercedes-Benz S500L 4MATIC.'),
(3, 1, 3, 7, 2022, 850000, 'CNY', 18000, TRUE, 'Mercedes-Benz S450L.'),
(5, 1, 3, 8, 2023, 520000, 'CNY', 11000, TRUE, 'Mercedes-Benz E300L. AMG-пакет.'),

-- Toyota
(3, 1, 4, 9, 2023, 220000, 'CNY', 15000, TRUE, 'Toyota Camry 2.5G. Гибрид.'),
(1, 1, 4, 9, 2022, 195000, 'CNY', 32000, TRUE, 'Toyota Camry 2.0G.'),

-- Honda
(3, 1, 5, 10, 2023, 180000, 'CNY', 9000, TRUE, 'Honda Civic 220TURBO.');

-- DataSources
INSERT INTO "DataSources" ("Name", "Country", "BaseUrl", "IsActive")
VALUES 
('Autohome', 'China', 'https://www.autohome.com.cn', TRUE),
('Che168', 'China', 'https://www.che168.com', TRUE),
('Cars.com', 'USA', 'https://www.cars.com', FALSE);

-- ========================================
-- 3. Проверка данных
-- ========================================
SELECT 'Markets' as TableName, COUNT(*) as RecordCount FROM "Markets"
UNION ALL
SELECT 'Brands', COUNT(*) FROM "Brands"
UNION ALL
SELECT 'Models', COUNT(*) FROM "Models"
UNION ALL
SELECT 'Dealers', COUNT(*) FROM "Dealers"
UNION ALL
SELECT 'Cars', COUNT(*) FROM "Cars"
UNION ALL
SELECT 'DataSources', COUNT(*) FROM "DataSources";
